platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

workspace 'WeatherMap'

xcodeproj 'WeatherMap'

use_frameworks!

pod 'ZipArchive'
pod 'Spring'
pod 'Alamofire'
#pod 'GPUImage'
pod 'SwiftyJSON'
pod 'Shimmer'
pod 'HanekeSwift'#, :git => 'https://github.com/Haneke/HanekeSwift.git'
#pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'

pod 'AMapSearch' #搜索服务SDK
pod 'MKMapViewZoom'

