# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace 'WeatherAroundUs'

xcodeproj 'WeatherAroundUs'

use_frameworks!

pod 'Spring'
pod 'Alamofire'
pod 'GPUImage'
pod 'SwiftyJSON'
pod 'Shimmer'
pod 'HanekeSwift'#, :git => 'https://github.com/Haneke/HanekeSwift.git'


